### ISSUE TITLE
我也写了一个抖音版，你的比我写得全面啊

### ISSUE THREAD

**Issue by WangCharlie** [mjl0602/flutter_tiktok#1]
地址 https://github.com/WangCharlie/douyin

**Comment by mjl0602** [comment]
兄弟，这也能开issue的吗……

其实我这个项目还有两个小问题，一个是评论列表在到顶时继续下拉无法触发BottomSheet的手势，另一个是PageView在最顶上的下拉刷新手势冲突一直没解决。
还有个我懒得写的，就是手动暂停时要显示一个暂停图标在视频中心，被动暂停则没有这个图标。本来是有的，我换播放器的时候生命周期也换了，就去掉了。

您能提PR指导下并修复如上问题的话，感激不尽。

**Comment by WangCharlie** [comment]
互相学习哈.. 偶然看到你这个  但是又没地方留言
