### ISSUE TITLE
你好，我发现项目的这些问题，能否收pr或一起维护

### ISSUE THREAD

**Issue by ahyangnb** [mjl0602/flutter_tiktok#13]
你好，你这个项目我非常敢兴趣，非常想一起维护或者提pr，我的github用户名：ahyangnb

目前项目需要维护的地方：
1.评论滑到顶部继续滑不会收起。
2.缺少长按提示对话框。
3.缺少右下角音频转动和左下角音频名轮播。
4.用户名页面目前是静态的。

希望能一起优化，把这个开源项目做好，目前我有多个上千人flutter群，到时候可以推广拉star。

**Comment by mjl0602** [comment]
你好，此项目原是一个商业项目，由于客户停止资金支持，所以我停止了对该项目的继续开发，改为开源项目。该项目技术上可以较好的展示flutter对于复杂交互的控制能力，我本人并无将其继续开发成完整抖音的计划（而且抖音后来也有改版）。

关于你提的问题：

1. 我在工作之余查过，在群里也问了一下，没有得到答案。我也懒得费很多时间去找如何增加这个手势。此处欢迎你的pr，我也可以学习一下。
2. 长按提示并不难写，这不是问题
3. 同上
4. 同上

不过如果您有兴趣继续开发，十分欢迎您的pr。目前我主要在FlutterCandies的QQ群里活动，您要是想与我直接沟通，可以先进群（181398081），群里还有flutter作者和一些知名库的作者。我欢迎任何人继续开发这个项目，只是原先的代码，并未经过专门整理，可能缺少一些必要的注释，希望可以克服一下。
