### ISSUE TITLE
clone下来的项目报错

### ISSUE THREAD

**Issue by xiaoshu0629** [mjl0602/flutter_tiktok#14]
![image](https://user-images.githubusercontent.com/30100675/97522304-6c91ee00-19da-11eb-8916-a0fa1cca5f7d.png)

**Comment by mjl0602** [comment]
试试在iOS目录下pod install 或者 pod update

**Comment by xiaoshu0629** [comment]
> 试试在iOS目录下pod install 或者 pod update

运行pod install和 pod update都不行，我的xcode是12.0，flutter是1.24.0，跟我的flutter版本有关系吗

**Comment by mjl0602** [comment]
老问题了，只能自己看看……和Flutter关系不太大，主要是Pod或者swift部分导致的，有时候就会这样。
