### ISSUE TITLE
多次上下滑动后，App崩溃

### ISSUE THREAD

**Issue by xushijie10086** [mjl0602/flutter_tiktok#17]
作者提供了几个在线资源短视频作为mock数据。
初次加载homePage时，将mock的视频数据列表一次性添加到playerList 视频列表。
然而，在红米redMi 7A 真机运行时，不断上下翻动短视频页面。切换6-10次左右，App崩溃。
现在我还不知道什么原因。希望作者帮忙看看。感激。。

**Comment by mjl0602** [comment]
我已经修改了加载方式，不过之前的形式我也没出现过闪退。
