### ISSUE TITLE
当视频很多的时候会崩掉

### ISSUE THREAD

**Issue by KerwinZheng** [mjl0602/flutter_tiktok#2]
![image](https://user-images.githubusercontent.com/32670257/82874958-571b2280-9f69-11ea-96cf-df054a55ce8d.png)

**Comment by mjl0602** [comment]
你好，像截图这样一次加载太多视频显然是不明智的。

你可以通过管理这个数组来控制视频加载，如果想要新增，可以监听PageView滑动，在快要滑动到结尾时添加新的视频（再setState），如果想要释放一些内存，可以先释放掉一些很早之前的播放器，然后从数组移除旧的视频（再setState），来完成无限播放，并保持内存不会过载。
