### ISSUE TITLE
Error installing BIJKPlayer

### ISSUE THREAD

**Issue by wuyanghu** [mjl0602/flutter_tiktok#20]
Error running pod install
Error launching application on iPhone 11.

**Comment by mjl0602** [comment]
升级依赖后，就不会再出现这个问题。
已经在最新的代码中修复。

**Comment by ceeyang** [comment]
我用 clashX 
配置代理如下：
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
其他软件同理
