### ISSUE TITLE
The named parameter 'shadowThemeOnly' isn't defined.

### ISSUE THREAD

**Issue by YuanDdQiao** [mjl0602/flutter_tiktok#21]
![err](https://user-images.githubusercontent.com/14799921/118441575-f35eac00-b71b-11eb-8007-5995d002f154.jpg)

**Comment by mjl0602** [comment]
Flutter 2.0 cause this, I suggest you remove this property and continue.

**Comment by mjl0602** [comment]
flutter升级导致的问题，删除属性再build就好了

**Comment by mjl0602** [comment]
已经在最新的代码中修复。
