### ISSUE TITLE
联系请求

### ISSUE THREAD

**Issue by RayRedDon** [mjl0602/flutter_tiktok#25]
你好 我们是一个短视频创业项目 看过你的代码之后希望与你建立联系

**Comment by mjl0602** [comment]
你好，本项目所有代码均可以商用。我无意再添加更多功能，感谢您对开源项目的关注。

**Comment by RayRedDon** [comment]
有没有兴趣加入区块链概念的短视频项目  我加你微信了  方便的话可以聊一聊

mjl0602 ***@***.***> 于2021年7月14日周三 下午3:02写道：
