### ISSUE TITLE
The named parameter 'scrollBehavior' isn't defined.

### ISSUE THREAD

**Issue by Deezee1390** [mjl0602/flutter_tiktok#28]
Getting issue in pageView.dart file. 

Error message "The named parameter 'scrollBehavior' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'scrollBehavior'."

Error message "The method 'copyWith' isn't defined for the type 'ScrollBehavior'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'."

Can you please help me with this issue?

Thanks,
Deepraj

**Comment by mjl0602** [comment]
Try update your Flutter SDK to newest version and relaunch your IDE.
