### ISSUE TITLE
build web 在safari并不能播放

### ISSUE THREAD

**Issue by kgdnone** [mjl0602/flutter_tiktok#29]
你好， build web版本， 丢到safari上， 播放不了视频， play函数调用了没有效果， 只有把video control显示出来，点击control的播放按钮才能播放， 有办法解决吗？？

**Comment by mjl0602** [comment]
web端有很多可见问题，可以研究后反馈给对应的库作者或flutter仓库。如果是我的问题，请反馈给我。
