### ISSUE TITLE
Backend support

### ISSUE THREAD

**Issue by venky9885** [mjl0602/flutter_tiktok#3]
Is it support frontend and backend

**Comment by mjl0602** [comment]
I think there is no need for short video app to support backend mode.

For background mode, you can see [befovy/fijkplayer]( https://github.com/befovy/fijkplayer).

**Comment by venky9885** [comment]
I am saying about  from firebase Videos will be get to app then play as a Stream of videos (many videos)

**Comment by mjl0602** [comment]
You can add url to url list in controller when  PageView scroll to last page.

**Comment by venky9885** [comment]
If we add from firebase url to  controller it will play as a stream of videos ,it is enough I think
