### ISSUE TITLE
How to use it in linux OS?

### ISSUE THREAD

**Issue by connLAN** [mjl0602/flutter_tiktok#36]
I am newbee for flutter, I can't run it at all, Could you give me some help?
I git clone it , and then do : 
flutter pub get
fluterr build web
google-chrome build/web/index.html

But I see nothing.  The linux terminal print some error messages, 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[62319:62319:0102/154436.247738:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[62156:62182:0102/154442.117641:ERROR:chrome_browser_main_ex

**Comment by mjl0602** [comment]
I'm sorry I cannot help you about run flutter on linux.
You can try a simple example of VideoPlayer repository in same environment. 
If VideoPlayer example launch successfully, you can try flutter_tiktok again.
