### ISSUE TITLE
star已给

### ISSUE THREAD

**Issue by herowws** [mjl0602/flutter_tiktok#39]
当我把tikTokVideoListController和video 单独抽离出来没有任何问题， pageview在home里我抽离homepage会涉及到很多很多东西，

**Comment by mjl0602** [comment]
pageview你直接自己写一个就完事了，补几个监听就好。

**Comment by herowws** [comment]
能帮我处理一下吗

**Comment by herowws** [comment]
我想我能请你喝杯咖啡

**Comment by herowws** [comment]
主要是才学习flutter 没有多久

**Comment by mjl0602** [comment]
别怕多，这里很简单的，你看看代码吧。

**Comment by herowws** [comment]
![image](https://user-images.githubusercontent.com/41428542/148914706-5b190d29-01da-408f-8d20-ed8ea6566f4d.png)
