### ISSUE TITLE
大哥能把环境发一下吗

### ISSUE THREAD

**Issue by pickupsb** [mjl0602/flutter_tiktok#4]

**Comment by mjl0602** [comment]
最新的flutter就行了

**Comment by pickupsb** [comment]
> 最新的flutter就行了

stable的吗

**Comment by mjl0602** [comment]
可以的，如果发现不兼容更高版本，请提issue到这里

**Comment by pickupsb** [comment]
> 可以的，如果发现不兼容更高版本，请提issue到这里

../1.12.13.hotfix.9sdk/flutter/packages/flutter/lib/src/rendering/editable.dart:1217:3: Error: Type 'TextRange' not found.
1.12.13 hotfix9 stable
请问这是啥问题

**Comment by mjl0602** [comment]
stable早就1.17了

**Comment by pickupsb** [comment]
> stable早就1.17了

1.17试过了，也是这个，我有两个sdk，切换了一下，是不是和原来的sdk有关系

**Comment by mjl0602** [comment]
看上去就是1.12没这个属性，1.17有这个属性就不会报错。
你切到1.17，然后重启vscode，再尝试运行试试。
