### ISSUE TITLE
 A ValueNotifier<bool> was used after being disposed & A TikTokVideoListController was used after being disposed.

### ISSUE THREAD

**Issue by gautamenbake** [mjl0602/flutter_tiktok#43]
Actually, I'm showing continuous video player [similar to homePage] on upper layer (means in separate screen).

I had opened videoplayer and close it, at the dispose time it shows these errors

I'm doing this in dispose method 
```
 @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    _videoListController.currentPlayer.pause();
    _videoListController.dispose();
    super.dispose();
  }
``` 

the error comes on this line on pause method of the video 
```
 @override
  Future<void> pause({bool showPauseIcon: false}) async {
    await Future.wait(_actLocks);
    _actLocks.clear();
    await init();
    if (!prepared) return;
    if (_disposeLock != null) {
      await _disposeLock?.future;
    }
    await this.controller.pause();
    **------------_showPauseIcon.value = true;------------**
  }

```
@mjl0602 looking for your help

**Comment by gautamenbake** [comment]
solved by removing this line from dispose
    _videoListController.dispose();

**Comment by gautamenbake** [comment]
`This comes if video properly loaded and you closes the videoplayer`

Once you have called dispose() on a ValueNotifier<bool>, it can no longer be used.
E[/flutter]() (11303): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:114
E[/flutter]() (11303): #1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:120

`When player is loading to load a video`

════════ Exception caught by foundation library ════════════════════════════════
A TikTokVideoListController was used after being disposed.

**Comment by gautamenbake** [comment]
@mjl0602 pls answer

**Comment by mjl0602** [comment]
Why the pause method called after dispose? You can simply remove player.showPauseIcon.dispose() in TikTokVideoListController.dispose to avoid this error.
