### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by cuongx** [mjl0602/flutter_tiktok#48]

**Comment by mjl0602** [comment]
Please provide your flutter version first.

**Comment by cuongx** [comment]
my flutter version 2.10.4

**Comment by mjl0602** [comment]
It seems like some problem about the gradle.

But I cannot help you with only one line log. So this issue is invalid until you provide full out your err log.

**Comment by cuongx** [comment]
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
