### ISSUE TITLE
视频比例不同时的问题

### ISSUE THREAD

**Issue by techistoner** [mjl0602/flutter_tiktok#49]
https://user-images.githubusercontent.com/5417557/170851432-ae4f0030-d24c-44eb-8f7d-cf871bf1864b.mp4
视频比例不同时
在预加载中 如果上一个视频是4：3 下一个是16：9
会出现 16：9的视频 加载时 还是4：3的播放器比例 并且会有短暂黑屏获取不到视频缩略图
直接跑源码也存在一样的问题。

**Comment by mjl0602** [comment]
VideoPlayer改来改去特性老是变，得看下他内部是怎么回事。

**Comment by techistoner** [comment]
![image](https://user-images.githubusercontent.com/5417557/170876967-a3db93d4-9569-4b94-b3e2-3c94f9e6cc4a.png)
应该是这样里的问题  原来设定了16比9的 然后碰到一些4：3的视频 就要之后才去拿player.value.aspectRatio视频的aspectRatio去赋值 提前给外层控件赋值的 话 应该就没问题了。

**Comment by mjl0602** [comment]
以前可以在屏幕外完成加载，现在不行了。

**Comment by mjl0602** [comment]
恢复了预加载功能，不是问题了。
