### ISSUE TITLE
不错的demo

### ISSUE THREAD

**Issue by yjt1216** [mjl0602/flutter_tiktok#59]
可以试着 添加网络权限 以及 检测网络变化相应处理

**Comment by mjl0602** [comment]
本项目只是展示flutter能力，目前不打算提供更多功能。
目前有兴趣去支持更多平台，但是因为media_kit问题较多，暂时还没有迁移过去。

**Comment by yjt1216** [comment]
> 本项目只是展示flutter能力，目前不打算提供更多功能。 目前有兴趣去支持更多平台，但是因为media_kit问题较多，暂时还没有迁移过去。

你这摸鱼呢

**Comment by mjl0602** [comment]
这项目本来是商业项目，结果甲方直接跑路失联了，就选取部分功能作为demo开源出来了。

**Comment by yjt1216** [comment]
没有先收钱吗
