### ISSUE TITLE
为什么会没有视频，只有声音呢？

### ISSUE THREAD

**Issue by 724607039** [mjl0602/flutter_tiktok#6]

**Comment by mjl0602** [comment]
iOS模拟器不支持flutter的texture传递。

真机上应该不会有这个问题

**Comment by 724607039** [comment]
好的我试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mjl0602"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上10:17
收件人:&nbsp;"mjl0602/flutter_tiktok"<flutter_tiktok@noreply.github.com&gt;;
抄送:&nbsp;"勿忘初心"<724607039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mjl0602/flutter_tiktok] 为什么会没有视频，只有声音呢？ (#6)





 
iOS模拟器不支持flutter的texture传递。
 
真机上应该不会有这个问题
