### ISSUE TITLE
一下子创建了所有播放器组件, 性能不太好吧

### ISSUE THREAD

**Issue by chengxushi** [mjl0602/flutter_tiktok#7]
你一下子创建了所有播放器组件, 当视频多了起来后, 性能消耗太大了吧, 我只是把视频增加到了20个的时候, 上下滑的时候我的手机已经发烫了

**Comment by mjl0602** [comment]
请先看目前的issue和readme，这个问题我重复回答很多次了。

关于批量创建，同时加载多个播放器可以有效的进行预加载。

关于性能，我在readme已经写的很清楚了，通过监听滑动去管理播放器，再改变数组内容并不困难，具体要加载几个播放器是由你自己决定的。

**Comment by chengxushi** [comment]
> 请先看目前的issue和readme，这个问题我重复回答很多次了。
> 
> 关于批量创建，同时加载多个播放器可以有效的进行预加载。
> 
> 关于性能，我在readme已经写的很清楚了，通过监听滑动去管理播放器，再改变数组内容并不困难，具体要加载几个播放器是由你自己决定的。

喔喔!!! 大师我悟到了!大佬

**Comment by chengxushi** [comment]
> 请先看目前的issue和readme，这个问题我重复回答很多次了。
> 
> 关于批量创建，同时加载多个播放器可以有效的进行预加载。
> 
> 关于性能，我在readme已经写的很清楚了，通过监听滑动去管理播放器，再改变数组内容并不困难，具体要加载几个播放器是由你自己决定的。

喔喔!!! 大师我悟到了!

**Comment by chengxushi** [comment]
> 请先看目前的issue和readme，这个问题我重复回答很多次了。
> 
> 关于批量创建，同时加载多个播放器可以有效的进行预加载。
> 
> 关于性能，我在readme已经写的很清楚了，通过监听滑动去管理播放器，再改变数组内容并不困难，具体要加载几个播放器是由你自己决定的。

喔喔!!  大师我悟到了!!!!!!!!!!!!!!!!!!!!!!
大佬请喝冰红茶

**Comment by chengxushi** [comment]
> 请先看目前的issue和readme，这个问题我重复回答很多次了。
> 
> 关于批量创建，同时加载多个播放器可以有效的进行预加载。
> 
> 关于性能，我在readme已经写的很清楚了，通过监听滑动去管理播放器，再改变数组内容并不困难，具体要加载几个播放器是由你自己决定的。

不好意思

**Comment by mjl0602** [comment]
欢迎来我们的qq群交流，FlutterCandies 群号:181398081
