### ISSUE TITLE
双击点赞的动画在播放器是AndroidView的情况下会失效

### ISSUE THREAD

**Issue by wangdedi1990** [mjl0602/flutter_tiktok#8]
hello，我的项目中播放器并不是flutter播放器，而是嵌的nativeView的播放器，发现这种情况下，点击动作没有生效，想知道作者有什么好的思路指点一下吗，感想

**Comment by mjl0602** [comment]
应该是需要设置Android View的手势事件，但是你的AndroidView估计也有手势，你可能要自己去处理手势冲突，例如单击在AndroidView的控件区域，应该不去触发点赞的逻辑判断。

总的来说不适合放在有手势AndroidView上用。

**Comment by ShawnLuo110** [comment]
连续点赞的时候不是单独渲染的点赞的UI   而是连着短视频一起渲染的看上去短视频就会卡顿  严重掉帧  这怎么处理的大佬

**Comment by mjl0602** [comment]
debug模式下，一些低端安卓机会卡是正常的，release模式下不会卡，很流畅。
